<a href="https://colab.research.google.com/github/KoGunWon/Linear-Algebra/blob/main/Lecture_16_Gauss_Jordan_Elimination_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

RREF (Gauss-Jordan Elimination)


In [1]:
import numpy as np

define row elementary row operations

In [2]:
def switch_row(A, i, j):
  @@@
  return A

def scale_row(A, i, scalar):
  if scalar == 0:
    raise ValueError("Cannot scale a row by zero")
  else:
    @@@@@@
  return A

def add_scaled_row(A, target, source, scalar):
  @@@@@@
  return A

SyntaxError: invalid syntax (<ipython-input-2-3ce6b31ec1f4>, line 2)

check elementary row operation works well

In [4]:
A = np.array([[2, -1, 3, -1], [1, 0, 2, 1], [1, -1, 1, -2]], float)
B = switch_row(A, 1,2)
C = scale_row(A, 3)
D = add_scaled_row(A, 1, 1, 2)

NameError: name 'switch_row' is not defined

1. Define variables

In [ ]:
def GJ(matrix):

  # 불러온 matrix값은 matrix 여야 함 (i.e., 2D array여야 함)
  if @@@@@@:
    raise ValueError(f"Input must be a 2D array (matrix), but got {@@@@@@@@}D.")

  pivot_i = 0 # 찾은 pivot 개수
  n_rows  = @@@@ # 주어진 matrix 의 row 수
  n_cols = @@@@ # 주어진 marix의 column 수
  rref_history = [matrix.copy()] # row operation 할 때마다 history로 저장
  n_row_operations = 0  # RREF 만들때까지 몇 번의 row operation 했는지 count

2.  column 에서 pivot 찾기, nonzero element 가 없으면, 다음 column으로, 찾았으면 pivot_i 번째 row 와 row switch

In [ ]:
def GJ(matrix):

  # 불러온 matrix값은 matrix 여야 함 (i.e., 2D array여야 함)
  if @@@@@:
    raise ValueError(f"Input must be a 2D array (matrix), but got {@@@@}D.")

  pivot_i = 0 # 찾은 pivot 개수
  n_rows  = @@@@ # 주어진 matrix 의 row 수
  n_cols = @@@@ # 주어진 marix의 column 수
  rref_history = [matrix.copy()] # row operation 할 때마다 history로 저장
  n_row_operations = 0  # RREF 만들때까지 몇 번의 row operation 했는지 count

  ################################################
  for cols in range(n_cols):
    if @@@: # column 이 row 보다 많을 때, 가능한 pivot 수에 따라서 다음 column은 조사할 필요 없음.
      break

    # column 안에 nonzero element 있는지 확인 (np.nonzero)
    non_zero_order = @@@@@
    if @@@@@: # nonzero element가 없으면 다음 column으로
      continue

    elif @@@@: # nonzero element가 있으면 row 위치 switch, (*스위치를 꼭 해야하는 것은 아님)
      matrix = switch_row(matrix, @@@@, @@@@)

      ### row operation 하였으면 다음과 같이 history와 row operation count 추가
      n_row_operations = n_row_operations + 1
      rref_history.append(matrix.copy())


3. 찾은 pivot 이 1이 되도록 scaling

In [ ]:
    matrix = scale_row(matrix, @@@@, @@@@)

    ### elementary row operation 하였으면 다음과 같이 history와 row operation count 추가
    n_row_operations = n_row_operations+1
    rref_history.append(matrix.copy())

4. pivot의 위 아래가 0이 되도록

In [ ]:
    for rows in range(n_rows):
      if @@@@@: # pivot 순서의 row 에 대해서는 계산할 필요없음.
        continue
      elif @@@@@: # 이미 element 가 0 이면 해당 row 에 대해서는 row operation 할 필요 없음
        continue
      else:
        matrix = add_scaled_row(matrix, @@@@, @@@@, @@@@)  # pivot이 위치한 column의 element가 0이 되도록 계산
        n_row_operations = n_row_operations + 1

    rref_history.append(matrix.copy()) # 여기에서는 RREF history에 마지막 결과만 저장

5. pivot 을 찾았고 계산을 다하였으면, pivot_i +1, 최종 형태

In [17]:
import numpy as np

def switch_row(matrix, i, j):
    matrix[[i, j], :] = matrix[[j, i], :]
    return matrix

def scale_row(matrix, i, scale_factor):
    matrix[i, :] *= scale_factor
    return matrix

def add_scaled_row(matrix, src, tgt, factor):
    matrix[tgt, :] += matrix[src, :] * factor
    return matrix

def GJ(matrix):  #한번에 짜고자 하면 5번을 짜면 된다

  # 불러온 matrix값은 matrix 여야 함 (i.e., 2D array여야 함)
  if not isinstance (matrix, np.ndarray) or matrix.ndim != 2:
    raise ValueError(f"Input must be a 2D array (matrix), but got {matrix.ndim}D.")

  pivot_i = 0 # 찾은 pivot 개수
  n_rows, n_cols = matrix.shape # 주어진 matrix 의 row 수
 # 주어진 marix의 column 수
  rref_history = [matrix.copy()] # row operation 할 때마다 history를 list로 저장
  n_row_operations = 0  # RREF 만들때까지 몇 번의 row operation 했는지 count

  for cols in range(n_cols):
    if pivot_i >= n_rows: # column 이 row 보다 많을 때, 가능한 pivot 수에 따라서 다음 column은 조사할 필요 없음.
      break

    # column 안에 nonzero element 있는지 확인 (np.nonzero)
    non_zero_order = np.nonzero(matrix[pivot_i:, cols])[0] + pivot_i

    if non_zero_order.size == 0: # nonzero element가 없으면 다음 column으로
      continue

    elif non_zero_order[0] != pivot_i: # nonzero element가 있으면 row 위치 switch, (*스위치를 꼭 해야하는 것은 아님)
      matrix = switch_row(matrix, pivot_i, non_zero_order[0])

      ### row operation 하였으면 다음과 같이 history와 row operation count 추가
      n_row_operations = n_row_operations + 1
      rref_history.append(matrix.copy())

    scale_factor = 1.0 / matrix[pivot_i, cols]
    matrix = scale_row(matrix, pivot_i, scale_factor)

    ### row operation 하였으면 다음과 같이 history와 row operation count 추가
    n_row_operations = n_row_operations+1
    rref_history.append(matrix.copy())

    for row in range(n_rows):
      if row == pivot_i: # pivot 순서의 row 에 대해서는 계산할 필요없음.
        continue
      elif matrix[row, cols] == 0: # 이미 element 가 0 이면 해당 row 에 대해서는 row operation 할 필요 없음
        continue
      else:
        factor = -matrix[row, cols]
        matrix = add_scaled_row(matrix, pivot_i, row, factor)  # pivot이 위치한 column의 element가 0이 되도록 계산
        n_row_operations = n_row_operations + 1

    rref_history.append(matrix.copy()) # 여기에서는 RREF history에 마지막 결과만 저장

    pivot_i = pivot_i + 1

  return matrix, rref_history, n_row_operations

결과 체크

In [18]:
A = np.array([[2, -1, 3, -1], [1, 0, 2, 1], [1, -1, 1, -2]], float)
rref_A, history, n_row_oper = GJ(A)
print('RREF')
print(rref_A)
print('')
print(f'Total elementary operations: {n_row_oper}')
print('')

for i in range(len(history)):
  print(f"order {i} \n {history[i]} \n")

RREF
[[1. 0. 2. 1.]
 [0. 1. 1. 3.]
 [0. 0. 0. 0.]]

Total elementary operations: 6

order 0 
 [[ 2. -1.  3. -1.]
 [ 1.  0.  2.  1.]
 [ 1. -1.  1. -2.]] 

order 1 
 [[ 1.  -0.5  1.5 -0.5]
 [ 1.   0.   2.   1. ]
 [ 1.  -1.   1.  -2. ]] 

order 2 
 [[ 1.  -0.5  1.5 -0.5]
 [ 0.   0.5  0.5  1.5]
 [ 0.  -0.5 -0.5 -1.5]] 

order 3 
 [[ 1.  -0.5  1.5 -0.5]
 [ 0.   1.   1.   3. ]
 [ 0.  -0.5 -0.5 -1.5]] 

order 4 
 [[1. 0. 2. 1.]
 [0. 1. 1. 3.]
 [0. 0. 0. 0.]] 



RREF 만드는 과정에서 사용한 elementary operation 을 통해서 역행렬 구하는 알고리즘으로 확장 가능.